### ISSUE TITLE
Compatibility with Notebook

### ISSUE THREAD

**Issue by brichet** [jupyterlab/jupyter-chat#105]
### Problem

The chat extension is not compatible with Notebook application currently.

### Proposed Solution

Fix the extension to make it work with Notebook

**Comment by dlqqq** [comment]
This may be helpful: https://github.com/jupyterlab/jupyter-ai/pull/827

**Comment by brichet** [comment]
For traceability, the `@jupyter/react-components` (dependency of `jupyterlab-chat`) was missing form the shared scope of Notebook: https://github.com/jupyter/notebook/pull/7530

**Comment by brichet** [comment]
An other related issue, which leads to unexpected behavior with the side panel https://github.com/jupyter/notebook/issues/7534

This could be fixed here, but I would expect it to be fixed upstream instead.
