### ISSUE TITLE
Use dataclass models instead of untyped dictionaries in `YChat` Python API

### ISSUE THREAD

**Issue by dlqqq** [jupyterlab/jupyter-chat#115]
### Problem

The `YChat` API expects a dictionary in many areas of the code. For example, the `YChat.get_users()` and `YChat.get_message()` methods return dictionaries, but there's no indication to developers what the types of these dictionaries are, or what keys are available.

### Proposed Solution

Use `dataclass` models instead of dictionaries for the `YChat` Python API. `dataclass` should be preferred over native dictionaries as much as possible on any developer API surface, but the `YChat` API should be prioritized.

Furthermore, the models & attributes within the models should be documented with docstrings. This will make it easier to develop extensions on top of `jupyterlab-chat` if IDE intellisense is available.

**Comment by krassowski** [comment]
Would `TypedDict` or `dataclass` instead work? Adding pydantic closer to core means more dependency conflicts and packaging issues.

**Comment by dlqqq** [comment]
@krassowski Thanks for calling this out. I agree; if we don't need the extra features provided by Pydantic, it seems preferable to use `dataclass`, as it offers a similar API and is native to Python.

I would also add that if we run into issues with `dataclass`, we should feel free to use Pydantic instead. Pydantic v2 is a very common dependency, and it should be safer than many of the dependencies already being pulled in by `jupyterlab-chat`.

**Comment by ellisonbg** [comment]
I think `dataclass` is a reasonable approach for this case.

**Comment by dlqqq** [comment]
I've updated the title & description of this issue accordingly. Thanks folks!
