### ISSUE TITLE
`YChat` should not require an index to update a message

### ISSUE THREAD

**Issue by dlqqq** [jupyterlab/jupyter-chat#120]
## Description

To update a message in `YChat` (in response to a human user editing a message or Jupyter AI streaming a response), an index is required. See the type signatures for these two methods:

```python
def update_message(self, message: dict, index: int, append: bool = False):
    ...

def set_message(self, message: dict, index: Optional[int] = None, append: bool = False) -> int:
    ...
```

## Proposed solution

1. Add an observer on `self._ymessages` to maintain a lookup table between message IDs and the index in the list. This can be stored in a dictionary whose keys are message IDs and whose values are indices.
2. Update `update_message()` to just accept a `message: Message` argument and an `append: bool` argument. The method should reference the lookup table to find the right index from the message ID.
3. Remove `set_message()`, since developers will always know whether they are adding / updating a message. To make this more obvious, you could define a new dataclass that looks like:

    ```python
    class NewMessage:
        ... # same as `Message`, but without an ID
    ```
    
    Then, update `add_message` to accept `NewMessage` instead of `Message` and return the new message ID. That way, consumers don't have to generate their own UUID, and always know if they're adding/updating a message based on whether they have a message ID or not.

**Comment by brichet** [comment]
:+1: @dlqqq thanks for the suggestion.
