### ISSUE TITLE
Releases will have two version bumps

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyter-chat#15]
Hi @brichet it looks like we independently arrived at somewhat similar monorepo implementations. I am working on https://github.com/jupyterlab/jupyter-collaboration/pull/280 and in there I noticed that I have to short-circuit if any changes were made to the git, see the `bump_version.py` script. This is because of jupyter-releaser running the bump action for each of the python packages (https://github.com/jupyter-server/jupyter_releaser/issues/567). This is just to let you know that currently the release check in this repo also bumps two versions, taking an extract from logs:

```
Changes:
 - chat-jupyter: 0.1.0 => 0.1.1
 - jupyterlab-collaborative-chat: 0.1.0 => 0.1.1
 - jupyterlab-ws-chat: 0.1.0 => 0.1.1

lerna info auto-confirmed
lerna info execute Skipping git tag/commit
lerna info execute Skipping git push
lerna info execute Skipping releases
lerna success version finished
Setting up build environment for missing dependencies
0.1.1
0.1.1
COMMAND: ../../scripts/bump-version.sh patch
lerna notice cli v6.4.1
lerna info ci enabled
lerna info current version 0.1.1
lerna notice FYI git repository validation has been skipped, please ensure your version bumps are correct
lerna WARN force-publish all packages
lerna info Assuming all packages changed
lerna WARN version Skipping working tree validation, proceed at your own risk

Changes:
 - chat-jupyter: 0.1.1 => 0.1.2
 - jupyterlab-collaborative-chat: 0.1.1 => 0.1.2
 - jupyterlab-ws-chat: 0.1.1 => 0.1.2
```

**Comment by brichet** [comment]
Thanks @krassowski for opening this, I hadn't noticed this issue.

**Comment by brichet** [comment]
Closing it, since there is only one python package after https://github.com/jupyterlab/jupyter-chat/pull/100
