### ISSUE TITLE
Set up the releaser workflow

### ISSUE THREAD

**Issue by brichet** [jupyterlab/jupyter-chat#34]
Task list to set up the releaser workflow:
- [x] Add the `jupyterlab releaser bot` Github App (done by default)
- [x] Create a "release" environment
- [x] Add `APP_ID` variable, `NPM_TOKEN` and `APP_PRIVATE_KEY` secrets to that environment (coming from the Github app)
- [x] Configure the ruleset on branch and tag to allow the Github app to bypass it

cc @jtpio

**Comment by brichet** [comment]
thanks @jtpio 
I can't see the `NPM_TOKEN` in the secrets. Is it not required too?

**Comment by jtpio** [comment]
It's in the Actions secret:

![image](https://github.com/jupyterlab/jupyter-chat/assets/591645/3504a479-7d46-4cdc-ac57-f9a26b8209cd)

**Comment by jtpio** [comment]
Ah, it's probably equivalent. For reference I looked at the `jupyter-collaboration` repo since it was recently set up to use the GitHub for releasing. Both `APP_PRIVATE_KEY` and `NPM_TOKEN` are accessed via `secrets.`:

https://github.com/jupyterlab/jupyter-collaboration/blob/adb51b0efd22e63c0110c08dacfc61aebb8ef559/.github/workflows/publish-release.yml#L28

https://github.com/jupyterlab/jupyter-collaboration/blob/adb51b0efd22e63c0110c08dacfc61aebb8ef559/.github/workflows/publish-release.yml#L42

**Comment by jtpio** [comment]
Also it looks like we still to update the releaser workflows to use the GitHub app, as there is still a mention of `ADMIN_GITHUB_TOKEN`:

https://github.com/jupyterlab/jupyter-chat/blob/4b34bf41bcd47ff1a267a9bf85f6b884b389e2ba/.github/workflows/publish-release.yml#L29

**Comment by brichet** [comment]
Yes, I saw that too, I'll open a PR with an update

**Comment by brichet** [comment]
The releaser workflow failed to publish assert https://github.com/jupyterlab/jupyter-chat/actions/runs/9118046663/job/25070279419#step:5:157.
It seems to be related to a PyPI token.

**Comment by jtpio** [comment]
Could it be because there is a `pyproject.toml` file, but no Python package to publish? https://github.com/jupyterlab/jupyter-chat/blob/main/pyproject.toml

Do we need this file, or could the releaser config be moved to the `package.json` and this file be deleted?

**Comment by brichet** [comment]
There are python packages : https://github.com/jupyterlab/jupyter-chat/blob/f2288cf39222ae6c90a385dff10858c7edc5d769/pyproject.toml#L39

**Comment by jtpio** [comment]
Ah ok, then yes we need to set up the project on PyPI.

The easiest would probably to publish a placeholder package (with version `0.0.0a0`), and set up the trusted publisher via the settings page of the project on PyPI.

**Comment by jtpio** [comment]
Also since this repo is under the `jupyterlab` org (https://github.com/jupyterlab/frontends-team-compass/issues/247) we could move the package to the Jupyter organization on PyPI, and put it under the JupyterLab team, once a first version is published.

**Comment by jtpio** [comment]
That's strange, the `jupyterlab-release-bot` should normally be able to publish the npm package directly without a placeholder.

**Comment by jtpio** [comment]
Oh, maybe it's because that package is under the `@jupyter` scope and not the `@jupyterlab` scope.

If so, we can update the `NPM_TOKEN` to be the one for `jupyter-release-bot` (and not `jupyterlab-release-bot`), and check if it helps.

**Comment by jtpio** [comment]
OK I have updated the `NPM_TOKEN`:

![image](https://github.com/jupyterlab/jupyter-chat/assets/591645/3dac1ca2-15b5-4ff1-af3c-a5e684c85f33)

Let's try again and see if that fixes it?

**Comment by brichet** [comment]
> OK I have updated the `NPM_TOKEN`:
> 
> ![image](https://github.com/jupyterlab/jupyter-chat/assets/591645/3dac1ca2-15b5-4ff1-af3c-a5e684c85f33)
> 
> Let's try again and see if that fixes it?

Good catch, thanks for the update

**Comment by brichet** [comment]
Looks like it worked: :tada: https://github.com/jupyterlab/jupyter-chat/releases

- https://www.npmjs.com/package/@jupyter/chat
- https://www.npmjs.com/package/jupyterlab-collaborative-chat
- https://www.npmjs.com/package/jupyterlab-ws-chat


> Is there any reason for naming the package `@jupyter/chat`, or could `@jupyterlab/chat` also work?

At first, it was named `@jupyterlab/chat`. Then we change it because it can be used with other jupyter-frontends applications.

For the extensions, since they were using the jupyterlab extension system, I choose to prefix them with `jupyterlab_` (even if they should work with Notebook as well).

I don't have a strong opinion on it. Are you aware of any open discussion of org subprojects since the switch to jupyter-frontends?

**Comment by jtpio** [comment]
OK thanks for the extra context :+1: 

I think it's fine to keep the `jupyterlab_` prefix, as most of the ecosystem uses it. And even if other frontends such as Notebook 7 are different applications, they are still based on JupyterLab components.

**Comment by brichet** [comment]
Thanks @jtpio for helping with the release workflow
