### ISSUE TITLE
Support for streaming messages

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyter-chat#52]
### Problem

Currently messages are added to the chat in one go. See this screencast as an example:

[a screencast showing the Codestral extension in JupyterLite](https://github.com/jtpio/jupyterlab-codestral/assets/591645/b63a84de-32bf-449c-8b48-7d71494b88b9)

However most of the AI chat UIs stream responses to the user, for example:

[mistral-ai-chat.webm](https://github.com/jupyterlab/jupyter-chat/assets/591645/cfdc3401-eb48-4b13-8787-665f9dca34cf)

### Proposed Solution

Add optional support for streaming messages, which could be enabled via the settings editor or by extensions.

### Additional context

This would be useful for AI extensions using `jupyter-chat` for interacting with some online AI providers, such as https://github.com/jtpio/jupyterlab-codestral

**Comment by jtpio** [comment]
This might already be possible in some way by a plugin, by calling the `updateMessage` method:

https://github.com/jupyterlab/jupyter-chat/blob/5cf395597cfa09a10fc8793830640f34d82b23c4/packages/jupyter-chat/src/model.ts#L76-L85

**Comment by brichet** [comment]
> This might already be possible in some way by a plugin, by calling the `updateMessage` method:

Yes, this is possible but will call the `RendermimeMarkdown` for the whole content on every update.

To avoid this we should provide an option in `updateMessage()` to append the content of the renderer to the dom:

https://github.com/jupyterlab/jupyter-chat/blob/5cf395597cfa09a10fc8793830640f34d82b23c4/packages/jupyter-chat/src/components/rendermime-markdown.tsx#L78-L80

**Comment by dlqqq** [comment]
@brichet Can this issue be closed now? Seems like the update message PR makes this possible. 

I'm not sure if there's a use-case for disabling message streaming; I think we can open another issue to track that if needed.

**Comment by brichet** [comment]
Yes, this issue can be closed.

> I'm not sure if there's a use-case for disabling message streaming; I think we can open another issue to track that if needed.

Currently, there is no concept of streaming in the chat extension. There is only a way to update a message.
I think that this concept is really related to generative AI stuff (correct me if I'm wrong), so a feature to disable message streaming would make more sense in `jupyter-ai`.
