### ISSUE TITLE
Path configuration for .chat files

### ISSUE THREAD

**Issue by mvallet91** [jupyterlab/jupyter-chat#61]
### Problem

The `.chat` files are created in the home directory of JupyterLab. It would be nice to be able to specify the path for chat files so users can put them into a `chats` folder, or admins (for instance using JupyterHub) can store them in a different path to minimize confusion for novice users.

### Proposed Solution

Enable configuration or something like a `jupyterlab_collaborative_chat_config.py` that is processed on startup, where the path can be specified.

**Comment by brichet** [comment]
Thanks for opening this @mvallet91.

When creating a chat file, you can specify an existing directory in the dialog, like `chats/general.chat` if the `chats` directory already exists.
We could add a setting for a default chat directory, and the path would be relative to this directory.

The left panel also provides a list of existing chat files, as a shortcut to open it (in the left panel).
We have deliberately limited the exploration to the root directory, to avoid extra computation if jupyterlab run in a huge file system.
If we provide a setting for a root chats directory, we should probably update also the directory to explore in the left panel.

**Comment by mvallet91** [comment]
Thank you @brichet. 

So, for `user-a` and `user-b` to have a collaborative chat, they would have to have the same root directory? 

Just to get it right, as I understand it, JupyterHub would start Jupyter in `/home/user-a` and in `/home/user-b`, respectively. And currently, they cannot chat since `jupyter-chat` couldn't read a `/home/shared-chats/CHAT1.chat`, even if they try to create it with that path. Is that correct? Is there another way for them to have access to the same chat?

**Comment by brichet** [comment]
There is special case for collaboration in jupyterhub, you need to set up a collaborative server, but I never tried so I can tell more than that.
https://github.com/jupyterhub/jupyterhub/blob/main/docs/source/tutorial/collaboration-users.md (thanks @trungleduc for the link)

**Comment by mvallet91** [comment]
Thank you, I'll check it out.
