### ISSUE TITLE
Improve the `dev-install` script

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyter-chat#64]
The top-level `package.json` has a `dev-install` script here:

https://github.com/jupyterlab/jupyter-chat/blob/025efd158ee42a9562d9f496e340feaefc90f88a/package.json#L36

However the underlying `packages` don't seem to be exposing such `script` in their own `package.json`.

It could be useful to add such script in the different `packages` to speed up the dev install, which would for example run the `jupyter labextension develop . --overwrite` command for the lab extensions.

**Comment by brichet** [comment]
Thanks for pointing it out @jtpio
