### ISSUE TITLE
Duplicated chats

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyter-chat#83]
## Description

Creating multiple chats with the same name is allowed and results in several identical chats.

## Reproduce

1. Click on "Create a chat"
2. Enter the name of the chat: "chat0"
3. Click on "Create a chat"
4. Enter the same name as before: "chat0"
5. See that `CHAT0` is duplicated in the chat list.

## Expected behavior

Maybe there should be an error saying that the chat already exists?

**Comment by brichet** [comment]
Thanks @davidbrochart for opening this.

Right, the side panel allows to open several times the same chat.
I observe the same behavior if I move a chat from the main area to the side panel (if the chat was already opened in the side panel).
